[package]
name = "rustyManager"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde-jsonlines = "0.6.0"
serde_json = "1.0"
tabled = { version = "0.16.0", features = [] }
